greenelab/annorxiver_manuscript

content/02.introduction.md
content/03.methods.md
content/04.results.md
content/05.discussion.md
content/06.conclusion.md
content/07.acknowledgements.md
content/metadata.yaml

This is a working outline of the annorxiver manuscript. I provided a title, section headers and filled in some talking points for certain sections of the paper. I expect content to change once more analyses are finished, but always good to have a starting point.

Outline Annorxiver Manuscript

---

content/03.methods.md

This PR contains description of the datasets that were used in this analysis.

Methods dataset

---

content/03.methods.md
content/manual-references.json

This PR contains description on how document vectors were created by using word2vec.

Methods Document Representation

---

content/03.methods.md
content/manual-references.json

This PR follows #5. Everything is now ready for review.

Methods - Dimensionality Reduction

---

content/03.methods.md

This PR contains methods description for training knn classifiers for journal recommendation.

Methods journal recommendation 

---

content/04.results.md

This PR contains section on preprint vs published odds ratio results.

Results preprint published

---

content/04.results.md

This PR contains blurb on biorxiv repository result figures. Pretty straight forward.

Results biorxiv pmc

---

content/04.results.md

This PR contains results section for biorxiv vs PMC comparison.

Results global comparison

---

content/03.methods.md

I tried to be as sequential as possible in this section for describing the distributions and how we generated candidate links.

Methods Section - Fill in missing links section

---

content/03.methods.md

This PR contains a description on how the SAUCIE model was trained.

Added SAUCIE model Description 

---

content/03.methods.md
content/manual-references.json

This PR updates the corpora comparison section to reflect the new additions to the analysis and removes an outdated citations for this section.

Updates corpora comparison sectionto reflect new additions

---

content/04.results.md
content/90.back-matter.md

This PR updates the corpora comparison results section. I added the corpora stats table, the KL divergence figure, updated odds ratio figures and supplemental odds ratio of PMC/Biorxiv vs reference figures. I also fixed a few parse issue to make manuscript render correctly.

Results corpora comparison

---

content/06.conclusion.md

Here is the conclusion section for the annorxiver manuscript.

Conclusion

---

content/07.acknowledgements.md
content/metadata.yaml

This contains data availability,  acknowledgements sections and CRedIT keywords to highlight author contributions.

Data Availability, Funding acknowledgements and CRedIT keywords

---

content/02.introduction.md

Here are my revisions for the introduction section.

Revisions for the Introduction Section

---

content/03.methods.md
content/manual-references.json

Here are my revisions for the methods section

Revisions for the Methods Section

---

content/05.discussion.md

Here are my revisions for the discussion section.

Revisions for the Discussion Section

---

build/assets/custom-dictionary.txt
content/02.introduction.md

This updates the intro section based on a full read :)

Revise intro based on full read

---

.github/workflows/manubot.yaml
build/README.md
build/environment.yml
build/pandoc/defaults/html.yaml
build/plugins/d3.html
build/plugins/inline-svg.html
build/plugins/math.html
build/themes/default.html

This PR updates manubot to hopefully fix my compilation issues.

Rootstock-2020-11-11 Update

---

.github/workflows/manubot.yaml
build/README.md
build/environment.yml
build/pandoc/defaults/html.yaml
build/plugins/d3.html
build/plugins/inline-svg.html
build/plugins/math.html
build/themes/default.html
content/04.results.md

I'm starting through the results. I had a couple questions/suggestions (as comments) in addition to these changes. I'll try to keep working on this branch through the first section, but please provide feedback and I'll incorporate it as I go. Thanks!

initial edits for results

---

.gitignore
content/01.abstract.md
content/03.methods.md
content/07.acknowledgements.md
content/metadata.yaml

This PR adds the abstract (<250 words), conflicting interest statement and added author stubs along with corresponding CRediT attributes.

Abstract authors

---

content/04.results.md
content/90.back-matter.md

I updated the figures to be panels instead of individual figures. Should be a lot easier to read now.

Figure Panels - Results Section 

---

content/03.methods.md
content/04.results.md
content/90.back-matter.md

Draft of revisions to results section

---

content/06.acknowledgements.md

I'm not required to have a competing interest statement, but this seems like a pretty reasonable one.

add MT competing interest statement

---

content/02.introduction.md
content/03.methods.md
content/04.results.md
content/05.conclusion.md
content/06.acknowledgements.md
content/90.back-matter.md

@danich1 I reviewed the paper and made some changes on wordings for you to consider. Most of them are trivial.
Some changes were made automatically by my editor (Emacs) because it doesn't like the trailing ^M on DOS file format. You can safely ignore them.

Review comments

---

content/03.methods.md

This PR updates the corpora comparison method section to be a bit more explicit on chosen tools and metrics.

Corpora comparison method rewrite

---

content/02.introduction.md
content/04.results.md
content/90.back-matter.md

This section updates the corpora comparison results based on collaborator feedback.

Corpora Comparison rewrite

---

content/01.abstract.md
content/02.introduction.md
content/03.methods.md
content/06.acknowledgements.md

This PR contains changes made per full run of the annorxiver manuscript. Updated abstract and majority of the method sections.

Made changes to first half of the document

---

content/04.results.md

Updated the document embedding PCA analysis per collaborator feedback.

PCA document embedding results rewrite

---

.gitignore
content/03.methods.md
content/04.results.md

Rewrite peer review time analysis per collaborator feedback.

Time results rewrite

---

.github/workflows/manubot.yaml

This PR is a test to see if I enabled docx build correctly.

Enabled docx?

---

build/assets/custom-dictionary.txt
content/04.results.md
content/05.conclusion.md
content/06.acknowledgements.md

This PR is a follow up off of the first set of changes within #59.

Casey-Larry changes part 2

---

content/02.introduction.md

This PR is one of many in the process of finalizing this paper. Ran grammarly on the introduction and then included the preprint linker citation (10.1007/s11192-021-03900-7)  mentioned in the emails.

Running Grammarly on Introduction

---

content/03.methods.md

Ran grammarly to fix small changes.

Ran grammarly on beginning of method section

---

content/03.methods.md

Final PR focusing on running grammarly on the methods section.

Grammarly methods part3

---

content/05.conclusion.md

Removed redundant statement but grammarly liked this section.

Grammarly discussion

---

content/04.results.md
content/90.back-matter.md

This PR contains the last part of the results section (minus Polka et al section in a different PR). The figures have been updated here along with small number of result updates. The only thing that needs to be updated is the website, which requires a process to finish running (Almost done 🤞🏾).

Ran Grammarly on last part of results section

---

content/metadata.yaml

I think this is now up to date including Dongbo's role in examining the data, David's statistical analyses, and my scoring of preprint publication pairs.

Credit Updates

---

content/03.methods.md

1. Updated stopwords lingo
2. Modified Spacy statement to make sure the default settings were explicit.
3. Grammarly changes

Methods reviewer requests part1

---

content/04.results.md
content/90.back-matter.md

This is the second half of editing the results section for the paper rewrite.
Main changes:
1. Updated the textual content title per reviewer request
2. Added the abstract only result as a supplemental figure for the paper
3. Fixed the label mismatch issue
4. Updated figures to have larger text/updated k-nearest-neighbors plot for cosine similarity proxy approach

Results Reviewer Request part2

---

content/05.conclusion.md
content/06.acknowledgements.md

1. Updated discussion and conclusion to incorporate details reviewers suggested we incorporate
2. Updated the data availability to incorporate the fee that may be charged for users not members of LDC.

Discussion Conclusion Reviewer Request

---

content/reviewers_response.md

Here is the response to reviewers. 
Have one more response to flesh out and a few sentences to restructure.
There were two sections within reviewer 2 (global matching comment and euclidean distance comment) that I honestly didn't understand. 
So those two responses may not make sense, but if there is something I'm missing let me know.

Reviewer response

---

content/03.methods.md
content/04.results.md
content/05.conclusion.md
content/90.back-matter.md

This PR contains last set of changes and manuscript is ready to resubmit (assuming collaborators do not have any changes they want to make).

Last set of changes 
